### ISSUE TITLE
Loading after fresh install fails: No module named 'deepface'

### ISSUE THREAD

**Issue by gnadenlos** [wallish77/wlsh_nodes#1]
Tried to install your nodes through ComfyUI Manger, but when starting it says:

No module named 'deepface'

This results in a complete failure to load your extension, not just a single node:

(IMPORT FAILED): C:\Users\xxx\ComfyUI_full\ComfyUI\custom_nodes\wlsh_nodes

**Comment by wallish77** [comment]
This is caused by trying to load in the `deepface` python module, which is not installed on your system.  I just pushed a version with the node and its dependencies disabled for now, as deepface has a lot of other requirements and the node isn't even functional currently.
