### ISSUE TITLE
How to use INFO from KSampler?

### ISSUE THREAD

**Issue by tusharbhutt** [wallish77/wlsh_nodes#10]
Nice to see a sampler that implies the various parameters can be saved... but what node accepts "INFO" as the input?

**Comment by wallish77** [comment]
There are a few image/prompt saving nodes in the IO tree that use INFO, but it seems there's something wrong currently that is preventing them from showing up for some people (#9).  The "Image Save with Prompt Data" is one of them.

**Comment by tusharbhutt** [comment]
OK thanks, seems like INFO is not common at all.  What is it's purpose compared to, say, STR or TEXT?

**Comment by tusharbhutt** [comment]
Sounds cool, hope yo get the image/prompt nodes working so it can be used :)
