### ISSUE TITLE
upscaled

### ISSUE THREAD

**Issue by RyanSHS6** [wallish77/wlsh_nodes#11]
How do you understand this "upscaled" and how to use it?please
![image](https://github.com/wallish77/wlsh_nodes/assets/118988972/4ff8505d-6fce-4622-988d-3bd56e78d03a)

**Comment by wallish77** [comment]
So, quick answer is: that's a bug and shouldn't be there.    Looks like it was left over from some other code. I just pushed a fix that removes it and fixes another bug that was in there.  I hadn't used that node in a while so I  guess I missed them. Thanks for bringing this to my attention!
