### ISSUE TITLE
Error when using SDXL

### ISSUE THREAD

**Issue by Magenta-6** [wallish77/wlsh_nodes#15]
Not sure whether this is set up to use SDXL.

Error occurred when executing KSamplerAdvanced (WLSH):

'pooled_output'

File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes\wlsh_nodes.py", line 107, in sample
samples = common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1207, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs)
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 97, in sample
samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 781, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

**Comment by wallish77** [comment]
That's strange.  This is a workflow for basic sdxl usage (single pass, no refiner) that works using the WLSH KSamplerAdvanced.  All that node does different is take the vanilla KSamplerAdvanced node and re-enable the denoising option (vanilla one uses a combination of end step and total steps to determine the 'denoising' percentage, I believe).  I'm using ComfyUI 1595 from 2023-10-20.  Does this workflow still have an error?  


![WLSH-sdxl-basic](https://github.com/wallish77/wlsh_nodes/assets/39662183/2142cda0-6912-4a97-9731-59dc0b7c4602)

**Comment by Magenta-6** [comment]
Thanks for getting back to me. That workflow is fine. 
It's the img2img that is tripping out. See screenshot. 
Quite possible I've wired up something wrong.
I copied your .png into the img loader and it failed at the First Pass Sampler.

![Screenshot_2023-10-27](https://github.com/wallish77/wlsh_nodes/assets/116250074/56f2e528-2dc5-4a4a-a6e8-a9a6cd52b13c)

**Comment by wallish77** [comment]
Are you using SDXL in that screenshot?  If so, the CLIP Encode node would need to be switched with the SDXL version.  If not... is the error output the same as the one from your post above?

**Comment by wallish77** [comment]
Here is a simple SDXL IMG2IMG workflow.  Try this one out.


![sdxl-img2img-basic](https://github.com/wallish77/wlsh_nodes/assets/39662183/5685002d-69e7-4154-86e5-a28ee287a0fa)

**Comment by Magenta-6** [comment]
I was in the middle of a reply when your last came in.
This is exactly what I was looking for.
Works fast, adds date modelname into filename, creates a scaled version.  Just what I need for massaging image styles.
I Really appreciate it.
Thanks heaps!
++++++++++++++++++++++++++++++++++++
Yes I'm using SDXL. Not quite sure where to find CLIP Encode (SDXL). 
If I right clik in the space and Add Node>WLSH Nodes>Conditioning
Is CLIP positivenegative XL (WLSH) the right one?
+++++++++++++++++++++++++++++++++
![2023-10-27-124400_zavychromaxl_v21_589346707778919](https://github.com/wallish77/wlsh_nodes/assets/116250074/2bd92607-9da8-413b-8d58-ffd43aeb0025)

**Comment by wallish77** [comment]
Yep, in that workflow I'm using CLIP  Positive/Negative XL w/ Text (which outputs the positive and negative prompt so you can plug it into my image saving node which will embed it as metadata in a similar way as Auto1111)

**Comment by wallish77** [comment]
I'll close this issue now as it seems resolved!
