### ISSUE TITLE
image save with file info error

### ISSUE THREAD

**Issue by kakachiex2** [wallish77/wlsh_nodes#17]
I'm getting the following errors wen traying to save image with prompt file info
![Screenshot 2023-11-15 151728](https://github.com/wallish77/wlsh_nodes/assets/1762112/73c91bb1-dc54-4622-903a-9602c204a7ff)

**Comment by wallish77** [comment]
I can't tell from your screenshot for sure, but I'm wondering if it's because of the output path.  If you leave that empty (so it defaults to the regular Comfy output) does it still give the error?

**Comment by kakachiex2** [comment]
Give the same error removing the path I' really like your implementation

**Comment by wallish77** [comment]
Ok, found the problem!  I had misread this as the Image Save with Prompt/Info node and couldn't find any issues (in code or in tests). Just saw that it's the version that does the file and found the bug in the code.  Newest commit should fix.

**Comment by kakachiex2** [comment]
Nice thanks wallish

**Comment by kakachiex2** [comment]
New error; know it save the image but not the text file
![Screenshot 2023-11-22 214741](https://github.com/wallish77/wlsh_nodes/assets/1762112/75a311f2-58ea-43c2-b796-8ae36d881e98)

**Comment by wallish77** [comment]
Whoops sorry didn't actually PUSH the fix.  Should be good in newest commit.

**Comment by kakachiex2** [comment]
How can I save the image in a folder with the date do I have to add some parameter

**Comment by kakachiex2** [comment]
Nitido pana work great thanks wallish
