### ISSUE TITLE
Empty Latent by Ratio node int output broken

### ISSUE THREAD

**Issue by drago87** [wallish77/wlsh_nodes#18]
When reading the int from the node i get this
![image](https://github.com/wallish77/wlsh_nodes/assets/6805712/597342e4-0acf-4fa7-9e5c-14e9696e40b9)
if i run the latent to a ksampler and make a image i get the right size

and i think it is 

`adj_width = width // 8` row 550
`adj_height = height // 8` row 551

that somehow breaks it. or you should return the `width,height` instead of the adjusted values (if there is not something i'm missing and it is not for the image size and something else. if so something that indicates that would be nice)

**Comment by wallish77** [comment]
Interesting.  What's strange is if you take the latent out of the Empty Latent by Ratio node and just decode it, it's the correct resolution (512x768), meaning that the `adj_width` and `adj_height` are working for creation of the latent image but not for the output width/height.  The floor division by 8 is necessary for the latent, but not the integer we want to return.  To make sure the output width/height is accurate to the image generated and not the input, I'll fix the return for those integers to effectively be `adj_width * 8` and `adj_height * 8`, which should match  Thanks for finding this!
