### ISSUE TITLE
Image Loader that provides Meta Data

### ISSUE THREAD

**Issue by gnadenlos** [wallish77/wlsh_nodes#2]
Have you thought about an alternative image loader that provides meta data, especially positive prompt(s) and negative prompt? 

This would fit well with the kind of nodes your pack already includes and would be very useful for separate upscaler and inpainting workflows, img2img workflows and even txt2img workflows if you want to test the prompts of another user in your own workflow without manually copying the prompts from their workflow.

**Comment by wallish77** [comment]
That's one of the nodes I've been working on, but I've been faced with the issue that unless the image was made with Auto1111 or my own image saving node, it can be pretty difficult to get prompt info (check out my "Prompt Inspector" repo to see how I'm pulling prompts out).

I think the way that Comfy embeds the workflow could be extracted for the prompt, assuming that everyone only used the same node(s) to put their prompts in.  Unfortunately that's not the case, so there isn't an easy way to check the list of nodes in a workflow and figure out what the positive and negative prompts are.  

The image loader to prompts is in-progress though, for sure.

**Comment by wallish77** [comment]
Feature implemented in commit b1b13386bfbb5e39b93379ac19e0474a10b7e16b
