### ISSUE TITLE
Python cache files breaking updates

### ISSUE THREAD

**Issue by condac** [wallish77/wlsh_nodes#26]
```
Update(git-clone) error: https://github.com/wallish77/wlsh_nodes / Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin
  stderr: 'error: The following untracked working tree files would be overwritten by merge:'
	__pycache__/__init__.cpython-311.pyc
	__pycache__/wlsh_nodes.cpython-311.pyc

```
Pythons __pycache__ should never be included in any git repository.

**Comment by wallish77** [comment]
Wow, don't know how they got added.  I actually had several files added that were not supposed to be in the last push and already purged one.  Thanks for pointing this out, I will remove!
