### ISSUE TITLE
The node is invalid and can not be added for use

### ISSUE THREAD

**Issue by vxkj1211** [wallish77/wlsh_nodes#9]
![image](https://github.com/wallish77/wlsh_nodes/assets/12245156/c60dd33e-036c-4c2c-82c8-af372ce7104f),"Image Save with Prompt Data (WLSH)"   "Save Prompt Info (WLSH)"   "Image Save with Prompt File (WLSH)"    The node is invalid and can not be added for use

**Comment by vxkj1211** [comment]
- The console doesn't have any error messages,no python errors

-the IO nodes list is displayed, but no new nodes can be added...

- Is previously added, the new node can not be added
- 
![image](https://github.com/wallish77/wlsh_nodes/assets/12245156/8a77dcbe-8b0f-4976-a1e7-28df43c8421b)

**Comment by wallish77** [comment]
Hmm, that's strange.  There was a slight change to that node in the commit around that time, but that should mean you only have to delete and re-add the node.  The fact that it isn't adding anything usually happens to me when the node is set up incorrectly.  Is your Comfy updated as well? I added in the image preview capability that relies on a previous Comfy update.

**Comment by vxkj1211** [comment]
Comfy updated latest version，Previous code can add nodes, I compared, comment out # “INFO”: (“Info”,) after all the nodes can be added to display,
![image](https://github.com/wallish77/wlsh_nodes/assets/12245156/81ec96db-8798-4519-8858-af0060fcba19)，# “INFO”: (“Info”,) ，The code can be commented out, but it will fail at runtime
![image](https://github.com/wallish77/wlsh_nodes/assets/12245156/41d503e6-ed20-4a96-a9b0-e085642d4a72)
I Am a novice, the code is not very understand, hope to help you,

**Comment by tusharbhutt** [comment]
I'm having a similar issue with no error messages appearing but in the IO menu, only the bottom two WLSH node load ("save positive prompt file" and "read prompt data from image") appear after selecting

**Comment by wallish77** [comment]
I just pushed a new commit that should be unrelated, but I'm curious if it changes anything.   Currently we're in the awkward state where it works on my system so without error messages I'm having a hard time tracking down what might be causing this. 

I'm still looking into it, though.

**Comment by tusharbhutt** [comment]
Still goobered :)

![image](https://github.com/wallish77/wlsh_nodes/assets/26264462/f440b3e4-bce1-49ea-8aeb-3d3fcfb48eb1)

**Comment by wallish77** [comment]
Are there any messages that appear in the console while Comfy is loading all the third party nodes?  The common link between the non-working nodes is the INFO input, but I'm not seeing why that wouldn't be working.  The only thing I can think of right now is another node that interacts with nodes and doesn't understand the made-up type "INFO"?

Still looking into it.

**Comment by tusharbhutt** [comment]
I don't get an error message in the startup (see below).  The IO nodes simply refuse to appear

```
-launch --use-pytorch-cross-attention --listen
** ComfyUI start up time: 2023-09-19 15:22:38.589435
Total VRAM 12287 MB, total RAM 16335 MB
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention

[rgthree] Optimizing ComfyUI reursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Prestartup times for custom nodes:
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   6.7 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy

### Loading: ComfyUI-Impact-Pack (V4.8.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.2)
### Loading: ComfyUI-Inspire-Pack (V0.14.2)
### Loading: ComfyUI-Manager (V0.29.1)
### ComfyUI Revision: 1469 [f895260e]
[SD Prompt Reader] Reader core version: 1.3.3.post1
C:\Applications\StableDiffusion\ComfyUI\python_embeded\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Comfyroll Custom Nodes: Loaded
hus' utility nodes: loaded
[tinyterraNodes] Loaded
EndelssSeaofStars Custom Nodes: Loaded
EndelssSeaofStars Custom Nodes: Loaded
C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
C:\Applications\StableDiffusion\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions
[Power Noise Suite]: 🦚🦚🦚    Squeaa-squee!!! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.
rgthree's comfy nodes: Loaded 15 exciting nodes.
Total VRAM 12287 MB, total RAM 16335 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 193 nodes successfully.

        "Success is not just about making money. It's about making a difference." - Unknown


Import times for custom nodes:
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\EndlessNodes
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\comfyui_otonx_nodes
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\Endless-Nodes
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_hus_utils
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-job-iterator
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\Comfy_KepListStuff
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Load_Image_With_Metadata
   0.0 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.1 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.1 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.2 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\bsz-cui-extras
   0.7 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   1.5 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.7 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   2.4 seconds: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
```

**Comment by wallish77** [comment]
Can anyone confirm what the last working commit was for those nodes?  commit b1b13386bfbb5e39b93379ac19e0474a10b7e16b was when the INFO portion was added, so I'm curious if any of them worked after that point or if that is the breaking point

**Comment by wallish77** [comment]
Also, the console in the browser may provide error messages when attempting to load those nodes and would hopefully explain why they won't.  Can you see if any messages appear? (F12 for developer mode on most browsers -> Console)

**Comment by tusharbhutt** [comment]
> Also, the console in the browser may provide error messages when attempting to load those nodes and would hopefully explain why they won't. Can you see if any messages appear? (F12 for developer mode on most browsers -> Console)

Here you go... I'll try turning off tiny Terra in a bit as that's the name that came up immediately in error


TypeError: inputData[1] is undefined
    INFO http://127.0.0.1:8188/extensions/tinyterraNodes/ttNwidgets.js:348
    ComfyNode http://127.0.0.1:8188/scripts/app.js:1252
    createNode http://127.0.0.1:8188/lib/litegraph.core.js:435
    callback http://127.0.0.1:8188/lib/litegraph.core.js:10517
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    inner_onMenuAdded http://127.0.0.1:8188/lib/litegraph.core.js:10533
    callback http://127.0.0.1:8188/lib/litegraph.core.js:10501
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    inner_onMenuAdded http://127.0.0.1:8188/lib/litegraph.core.js:10533
    callback http://127.0.0.1:8188/lib/litegraph.core.js:10501
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    inner_onMenuAdded http://127.0.0.1:8188/lib/litegraph.core.js:10533
    onMenuAdd http://127.0.0.1:8188/lib/litegraph.core.js:10537
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    processContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13327
    processMouseDown http://127.0.0.1:8188/lib/litegraph.core.js:6267
    processMouseDown http://127.0.0.1:8188/scripts/app.js:778
[litegraph.core.js:437:29](http://127.0.0.1:8188/lib/litegraph.core.js)
    createNode http://127.0.0.1:8188/lib/litegraph.core.js:437
    callback http://127.0.0.1:8188/lib/litegraph.core.js:10517
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    (Async: EventListener.handleEvent)
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    inner_onMenuAdded http://127.0.0.1:8188/lib/litegraph.core.js:10533
    callback http://127.0.0.1:8188/lib/litegraph.core.js:10501
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    (Async: EventListener.handleEvent)
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    inner_onMenuAdded http://127.0.0.1:8188/lib/litegraph.core.js:10533
    callback http://127.0.0.1:8188/lib/litegraph.core.js:10501
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    (Async: EventListener.handleEvent)
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    inner_onMenuAdded http://127.0.0.1:8188/lib/litegraph.core.js:10533
    onMenuAdd http://127.0.0.1:8188/lib/litegraph.core.js:10537
    inner_onclick http://127.0.0.1:8188/lib/litegraph.core.js:13894
    (Async: EventListener.handleEvent)
    addItem http://127.0.0.1:8188/lib/litegraph.core.js:13847
    addItem http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:63
    ContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13731
    ContextMenu http://127.0.0.1:8188/extensions/core/contextMenuFilter.js:11
    ContextMenu http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/contextMenuHook.js:86
    processContextMenu http://127.0.0.1:8188/lib/litegraph.core.js:13327
    processMouseDown http://127.0.0.1:8188/lib/litegraph.core.js:6267
    processMouseDown http://127.0.0.1:8188/scripts/app.js:778

​

**Comment by tusharbhutt** [comment]
Success! Kinda.

![image](https://github.com/wallish77/wlsh_nodes/assets/26264462/b34b4f92-aeb0-44cf-afd0-03c12f48f557)

Removing the TTN from the Custom folder did not help, but removing them from the web/extensions folder did.  Looks like **ttN.js** is the JavaScript that's interfering with your node. Or vice versa

**Comment by wallish77** [comment]
Interesting!  It seems like TTN doesn't recognize the "INFO" type (which isn't really a type) and errors out the node.  I'll see if I can find a workaround.

@vxkj1211 Are you also using TinyTerraNodes?

**Comment by tusharbhutt** [comment]
> Interesting! It seems like TTN doesn't recognize the "INFO" type (which isn't really a type) and errors out the node. I'll see if I can find a workaround.
> 
Is there a list of "types" that is a reference set?  When I removed TTN and ran the Image with save, I got an "unknown error" in the WebUI; will have to play with it some more after work

**Comment by tkocou** [comment]
This thread might be related to a coding problem which I discovered by accident. Unfortunately, the power supply is dying on the system used for coding. With parts arriving next week, I should be able to offer a fix.

**Comment by AntiKoS** [comment]
Same for me. I have TTN and I can't add 3 IO nodes.

**Comment by wallish77** [comment]
I would recommend those that use TTN to file an issue on their github, as I can't pinpoint how the code on this end would be altered to fit if it is indeed due to the "INFO" type being incompatible with TTN's interface modifications and I'm not familiar with their codebase enough to dig in.

**Comment by wallish77** [comment]
I just went ahead and created non-INFO variants for now.  Please check that they work without issue and if so I'll go ahead and close this for now.

**Comment by tusharbhutt** [comment]
Nope... still does not load "Save Prompt w/ Info"

I also stripped out all other custom nodes other than the Manager and it didn't show.

**Comment by wallish77** [comment]
Any new browser console errors?  Also, do the versions without info load correctly (e.g. Image Save with Prompt vs. Image Save with Prompt/Info)?

**Comment by vxkj1211** [comment]
我重新部署了一个blender comfyui 安装包，这个问题消失了！
1.之后更新comfyui版本，使用想同python环境和custom_nodes，问题依然存在……
2.解决办法：建议重新部署整个项目，或使用没问题的 comfyui 安装包
3.目前没发现是python环境和custom_nodes兼容的问题，
I redeployed a blender COMFYUI installation package and the problem went away!

1. After updating the COMFYUI version, using the same Python environment and custom_nodes, the problem remains...

2. Solution: it is recommended that you redeploy the entire project or use No problem comfyui installation package

3. No Python environment and custom_nodes compatibility issues have been identified

**Comment by vxkj1211** [comment]
![image](https://github.com/wallish77/wlsh_nodes/assets/12245156/1b8d5c71-1232-4c14-afb6-79a912249386)
Normal add and display...

**Comment by wallish77** [comment]
Great! As it seems like it may be a problem from ComfyUI installation issues (perhaps holdovers from previous upgrades or file changes?) rather than the code here, I'll close this issue for now!
